### ISSUE TITLE
 When downloading source as a zip, loading in gamemaker fails to load all sprites (updated)

### ISSUE THREAD

**Issue by alexkisser** [VectorSatyr/sonic-for-gms#2]
**Environment**
Please complete the following information:
 - Device: PC
 - OS: Windows 11
 - Version: no idea

**Steps To Reproduce**
1. Go to releases
2. Download source code.zip
3. Load yyp in gamemaker
4. All sprites missing

**Expected behavior**
Honestly expected for it to just work

**Actual behavior**
 loading in gamemaker fails to load all sprites

**Additional context**
Using 2022 lts

**Additional media**
None

**Comment by alexkisser** [comment]
updated to use bug report template

**Comment by alexkisser** [comment]
There are sprite assets, however they are all empty and game doesn't run, i’m at a relatives for the weekend so i’ll get back to you about the crash message, I have not tried downloading from the front page, and its only the sprites i’ve seen corrupted, I am not running gamemaker as an administrator because i never knew i would possible need to.

**Comment by alexkisser** [comment]
And also the 2022 lts i’m using is on steam.

**Comment by VectorSatyr** [comment]
Thank you. This issue is puzzling, as I am _also_ running GameMaker LTS from Steam and am able to load the project file without any issues. Please do let me know when you've verified any error messages you receive when running the game and whether the issue persists after launching with administrative privileges.

**Comment by alexkisser** [comment]
Ok, i will get back to you when i get back home.

**Comment by alexkisser** [comment]
way too many feather messages.

**Comment by alexkisser** [comment]
aaaand, the project just doesnt work on 2022 lts.

**Comment by VectorSatyr** [comment]
@alexkisser 

> way too many feather messages.

I've seen the feather messages, but none of them should be causing any issues with loading or executing the project. Could it be that you have "Strict Type mode" enabled?

> aaaand, the project just doesnt work on 2022 lts.

Please be more specific. What errors did you recieve when you actually tried to run the game? And you ran GameMaker with administrative priviliges?
I apologize for any inconvenience this is having for you. I've asked others to try to load the project in LTS 2022, and they were able to do so without issue (aside from the aforementioned Feather errors.) I'm not sure what other steps you could take besides a re-install of GameMaker LTS 2022 (this is something I also tried myself.)

**Comment by alexkisser** [comment]
The feather messages are from me loading in the newest ide.
And it seems to work fine here.
